version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest-browsers
    working_directory: ~/repo
    branches:
      only:
        - master
    steps:
      - checkout
      - restore_cache:
          name: Restore NPM dependencies
          keys:
            - npm-{{ checksum "package.json" }}
            - npm-
      - run:
          name: Install NPM dependencies
          command: npm install
      - save_cache:
          name: Save NPM dependencies
          paths:
            - ./node_modules/
          key: npm-{{ checksum "package.json" }}
      - run:
          name: Publish to GitHub Pages
          command: |
            if [[ -z $GH_NAME || -z $GH_EMAIL ]]; then
             echo "GH_NAME and GH_EMAIL variables must be set"
             exit 1
            fi

            git config user.name $GH_NAME
            git config user.email $GH_EMAIL

            npm run gh
